# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsx', '0002_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='old_code',
            field=models.CharField(max_length=100),
        ),
    ]
