# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsx', '0003_auto_20171129_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mac_addr', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('ip_addr', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='group_holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amsx.Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amsx.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amsx.Supplier'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Asset type'),
        ),
        migrations.AddField(
            model_name='dhcp',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amsx.Asset'),
        ),
    ]
