# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsx', '0004_auto_20171201_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='hostname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dhcp',
            name='ip_addr',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
