# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_auto_20171003_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='av_safe_pattern_date',
            new_name='safe_pattern_date',
        ),
        migrations.AlterField(
            model_name='computer',
            name='av_safe_version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Safe Version for AV Software'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='fde_software',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full-Disk Encryption(FDE) Software'),
        ),
    ]
