# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_auto_20171003_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='av_safe_version',
            new_name='safe_av_version',
        ),
    ]
