# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_auto_20171003_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='antivirus_software',
            new_name='av_software',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='antivirus_ver',
            new_name='av_version',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='fde_ver',
            new_name='fde_version',
        ),
    ]
