# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_auto_20171003_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='type',
            new_name='software_type',
        ),
        migrations.AlterField(
            model_name='computer',
            name='auto',
            field=models.IntegerField(choices=[(None, '-- Please choose a value --'), (0, 'Automatic'), (1, 'Manually')], editable=False),
        ),
    ]
