# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_auto_20171006_1449'),
        ('ams', '0006_auto_20171006_1606'),
    ]

    operations = [
    ]
