# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_auto_20171009_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcomputer',
            name='fde_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adcomputer',
            name='scan_status',
            field=models.IntegerField(default=0),
        ),
    ]
