# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0011_dhcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcomputer',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adcomputer',
            name='fde_status',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='adcomputer',
            name='scan_status',
            field=models.IntegerField(default=-1),
        ),
    ]
