# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='idol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idols.Idol'),
        ),
    ]
