# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_video_idol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
