# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0004_auto_20170821_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.CharField(default='undefined', max_length=200),
        ),
    ]
