# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0005_video_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='idol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idols.Idol'),
        ),
    ]
