# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ams', '0005_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('identification_code', models.CharField(max_length=30)),
                ('purchasing_at', models.DateTimeField(blank=True)),
                ('warranty_at', models.DateTimeField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True)),
                ('used_at', models.DateTimeField(blank=True)),
                ('validity_day', models.IntegerField(blank=True)),
                ('version', models.CharField(blank=True, max_length=30)),
                ('configuration', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=11)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('cost', models.IntegerField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('pv_number', models.CharField(blank=True, max_length=20)),
                ('eligibility12', models.DateTimeField(blank=True)),
                ('eligibility21', models.DateTimeField(blank=True)),
                ('flag', models.IntegerField(blank=True)),
                ('new', models.IntegerField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ams.DeviceType')),
                ('current_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_holder', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ams.Location')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ams.Manufacture')),
                ('next_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_holder', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ams.Platform')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ams.Supplier')),
            ],
        ),
    ]
