#!/usr/bin/python
import os
import sys
import logging
import argparse
import httplib2
import re
from apiclient.discovery import build
from oauth2client import tools
from Infra import *

try:
    import argparse
    parser = argparse.ArgumentParser(prog='mdm-list-devices', description='List all enrolled devices on Google MDM', parents=[tools.argparser])
    parser.add_argument('--fields', nargs ="*", help='fields of device info to list, default: serialNumber', default=['serialNumber'])
    parser.add_argument('--version', action='version', version='%(prog)s 1.0')
    flags = parser.parse_args()
except ImportError:
    flags = None
args = vars(flags)

SCOPES = [
    'https://www.googleapis.com/auth/admin.directory.device.mobile.readonly',
    ]


credentials = Gauth(SCOPES, flags)
http = credentials.authorize(httplib2.Http())
service = build('admin', 'directory_v1', http=http)

"""MDM Docs: https://developers.google.com/resources/api-libraries/documentation/admin/directory_v1/python/latest/index.html"""
result = service.mobiledevices().list(customerId='my_customer', orderBy='email', projection='BASIC', maxResults=200).execute()
devices = result['mobiledevices']
for device in devices:
	print(" - ".join([str(device[field]) for field in args['fields']]))









