#!/bin/bash
repo_path="."
dry_run=false
param_string=`getopt -o d --long path::,dry-run -n 'list-branch' -- "$@"`
eval set -- "$param_string"
while [[ true ]]; do
    #statements
    case "$1" in
        --path)
            case "$2" in
                "") shift 2 ;;
                *) repo_path=$2 ; shift 2 ;;
            esac ;;
        -d|--dry-run) dry_run=true ; shift ;;
        --) shift ; break ;;
        *) echo "Unknown option: ${1}" ; exit 1 ;;
    esac
done
if [[ ! -d $repo_path ]] && [[ "$repo_path" != "." ]]; then
    #statements
    echo "${repo_path} is not a valid repo path" ; exit 1 ;
else
    cd $repo_path
fi
i=0
for line in $(git branch -r); do
    #statements
    branch=$(echo ${line}|cut -d" " -f 1)
    IFS='/' read -r -a array <<< "$branch"
    branch=$(printf "%s/" ${array[@]:1})
    if [[ "$branch" != "/" ]] ; then
        branches[$i]=${branch:0:$((${#branch} - 1))}
        i=$(($i + 1))
    fi
done

echo $(printf "%s " ${branches[@]})|sort -u|tr ' ' '\n'